### ISSUE TITLE
Inquiry on Proof of Theorem 1

### ISSUE THREAD

**Issue by ykwon0407** [ermongroup/ssdkl#1]
Hello! I am not sure this is the right place but I have a simple question on the Proof of Theorem 1 in Appendix 1. (https://arxiv.org/pdf/1805.10407.pdf)

<img width="845" alt="screen shot 2019-03-04 at 11 03 19 am" src="https://user-images.githubusercontent.com/16724290/53706825-972b4c80-3e6f-11e9-8f16-b5051c719584.png">

In Figure, I manage to understand the derivation up to the equations (16)~(19), but hard to understand Equation (20).
When we compare Equation (17) and (20), while the (17) finds the point minimizer of negative of log posterior, the (20) finds the point minimizer of negative of log likelihood (as far as I understand..)

Could you elaborate on this derivation? 

Best,

**Comment by sangmichaelxie** [comment]
Hello,

we're trying to show here that solving the particular variational
optimization problem is the same as optimizing log likelihood, so equation
20 is the goal.
in equation 20 we do the integral over the dirac centered on \bar{\theta},
which is just the evaluation of the term being integrated at \bar{\theta}.
While this is log(p(y, \bar{\theta} | X)) = log(p(y | \bar{\theta}, X)) +
log(p(\bar{\theta} | X)), the extra log(p(\bar{\theta} | X)) can be treated
as constant since X and \bar{\theta} are independent without labels y (the
probabilistic dependence is like X -> y <- theta), and in our case we will
choose a uniform prior over \bar{\theta} (we should make this explicit)

**Comment by ykwon0407** [comment]
@sangmichaelxie 

I got it! I did not notice that the prior for $\theta$ is uniform. Thanks !!
